name: Run C++ Program

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Compile
        run: g++ main.cpp -o main

      - name: Run
        run: ./main
